"""update models

Revision ID: 48de06d4867d
Revises: 9e55c48c021b
Create Date: 2023-06-23 10:46:47.602962

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "48de06d4867d"
down_revision = "9e55c48c021b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_email", table_name="user")
    op.drop_column("user", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email", sa.VARCHAR(length=50), nullable=False))
    op.create_index("ix_user_email", "user", ["email"], unique=False)
    # ### end Alembic commands ###
